version: 0.2

phases:
  install:
    runtine-versions:
      nodejs: latest
    commands:
      - echo "installing node"
  pre_build:
    commands:
      - echo "we are at pre build stage"
  build:
    commands:
      - echo "we are at build stage"
      - echo "testing"
      - grep -Fq "Congratulations" index.html
      - buildExitCode=$?
    finally:
      - |
        if [ "$buildExitCode" -ne 0 ]; then
          badge_status=failing
          badge_colour=red
        else
          badge_status=passing
          badge_colour=green
        fi
      - curl -s "https://img.shields.io/badge/Build-$badge_status-$badge_colour.svg" > ${GithubBranch}-build.svg
      - aws s3 cp ${GithubBranch}-build.svg s3://${S3Bucket}/badges/${GithubBranch}-build.svg --acl public-read --cache-control no-cache
  post_build:
    commands:
      - echo "this is post build stage"
